In [ ]:
import pandas as pd
import numpy as np 
from sklearn.metrics.pairwise import linear_kernel
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import ndcg_score

In [ ]:
books = pd.read_csv('/content/drive/MyDrive/Ky1nam4/DoAnCuoiKy/Data_final/data_final/content-based/final_books_than30.csv')
books

,category,url,id,sku,name,price,rating_average,review_count,all_time_quantity_sold,description,specifications,seller_id,seller_sku,seller_name,seller_store_id,count_specification,attributes
0,Nhà sách tiki/sách tiếng việt/sách bà mẹ em bé...,https://tiki.vn/product-p141483251.html?spid=1...,141483251.0,8.070578e+12,Sách: Thai Giáo Theo Chuyên Gia - 280 Ngày Mỗi...,80500.0,5.0,58.0,508.0,"\nThai Giáo Theo Chuyên Gia, 280 Ngày, Mỗi Ngà...","{""name"": ""Th\u00f4ng tin chung"", ""attributes"":...",36846.0,3.544877e+12,Minh Long Book,36125.0,5,"{'id': 141483251.0, 'publisher_vn': 'Minh Long..."
1,Nhà sách tiki/sách tiếng việt/sách bà mẹ em bé...,https://tiki.vn/product-p125362334.html?spid=1...,125362334.0,8.806987e+12,Dinh Dưỡng Thai Kỳ (Bà Bầu Ăn Gì Giúp Con Phát...,103950.0,4.8,41.0,486.0,“Dinh dưỡng thai kỳ” giống như một cuốn bách k...,"{""name"": ""Th\u00f4ng tin chung"", ""attributes"":...",1.0,6.946825e+12,Tiki Trading,40395.0,7,"{'id': 125362334.0, 'publisher_vn': 'Booklife'..."
2,Nhà sách tiki/sách tiếng việt/sách bà mẹ em bé...,https://tiki.vn/product-p58213080.html?spid=58...,58213080.0,4.467229e+12,Montessori – Phương Pháp Giáo Dục Toàn Diện Ch...,95200.0,5.0,16.0,116.0,MONTESSORI – PHƯƠNG PHÁP GIÁO DỤC TOÀN DIỆN CH...,"{""name"": ""Th\u00f4ng tin chung"", ""attributes"":...",53660.0,1.012848e+12,Nhà sách Fahasa,51001.0,6,"{'id': 58213080.0, 'publisher_vn': '1980 Books..."
3,Nhà sách tiki/sách tiếng việt/sách bà mẹ em bé...,https://tiki.vn/product-p52798281.html?spid=52...,52798281.0,9.856063e+12,Phương Pháp Giáo Dục Sớm Montessori Cho Trẻ Từ...,79200.0,5.0,15.0,115.0,Bạn đang có con ở độ tuổi 0-3? Đã bao giờ bạn ...,"{""name"": ""Th\u00f4ng tin chung"", ""attributes"":...",53660.0,4.504642e+12,Nhà sách Fahasa,51001.0,5,"{'id': 52798281.0, 'publisher_vn': '1980 Books..."
4,Nhà sách tiki/sách tiếng việt/sách bà mẹ em bé...,https://tiki.vn/product-p532292.html?spid=253150,532292.0,2.601852e+12,Học Montessori Để Dạy Trẻ Theo Phương Pháp Mon...,70000.0,4.8,4.0,72.0,Học Montessori Để Dạy Trẻ Theo Phương Pháp Mon...,"{""name"": ""Th\u00f4ng tin chung"", ""attributes"":...",53660.0,4.983970e+12,Nhà sách Fahasa,51001.0,5,"{'id': 532292.0, 'publisher_vn': 'Đinh Tị', 'b..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16582,Nhà sách tiki/sách tiếng việt/sách y học,https://tiki.vn/product-p68668523.html?spid=68...,68668523.0,3.639356e+12,Y Học Phổ Thông Dành Cho Mọi Người - Chuyên Đề...,23750.0,5.0,1.0,3.0,"Sách là cẩm nang cần thiết trong mỗi gia đình,...","{""name"": ""Th\u00f4ng tin chung"", ""attributes"":...",53660.0,8.924942e+12,Nhà sách Fahasa,51001.0,2,"{'id': 68668523.0, 'publisher_vn': 'DNTN Minh ..."
16583,Nhà sách tiki/sách tiếng việt/sách y học,https://tiki.vn/product-p80358871.html?spid=80...,80358871.0,8.339947e+12,Y Học Phổ Thông Dành Cho Mọi Người - Chuyên Đề...,23750.0,5.0,2.0,4.0,"Sách là cẩm nang cần thiết trong mỗi gia đình,...","{""name"": ""Th\u00f4ng tin chung"", ""attributes"":...",53660.0,3.338262e+12,Nhà sách Fahasa,51001.0,2,"{'id': 80358871.0, 'publisher_vn': 'DNTN Minh ..."
16584,Nhà sách tiki/sách tiếng việt/sách y học,https://tiki.vn/product-p37793725.html?spid=37...,37793725.0,7.602028e+12,Y Học Phổ Thông Dành Cho Mọi Người - Chuyên Đề...,17100.0,4.8,4.0,17.0,Y Học Phổ Thông Dành Cho Mọi Người - Chuyên Đề...,"{""name"": ""Th\u00f4ng tin chung"", ""attributes"":...",53660.0,7.199800e+12,Nhà sách Fahasa,51001.0,1,"{'id': 37793725.0, 'publisher_vn': 'CN NXB Tha..."
16585,Nhà sách tiki/sách tiếng việt/sách y học,https://tiki.vn/product-p37151279.html?spid=37...,37151279.0,9.891892e+12,Y Học Phổ Thông Dành Cho Mọi Người - Chuyên Đề...,23750.0,4.7,6.0,36.0,Y Học Phổ Thông Dành Cho Mọi Người - Chuyên Đề...,"{""name"": ""Th\u00f4ng tin chung"", ""attributes"":...",53660.0,2.452895e+12,Nhà sách Fahasa,51001.0,1,"{'id': 37151279.0, 'publisher_vn': 'NXB Thanh ..."
16586,Nhà sách tiki/sách tiếng việt/sách y học,https://tiki.vn/product-p86981323.html?spid=11...,86981323.0,3.647241e+12,Khoa học hành vi trong răng hàm mặt,66000.0,0.0,0.0,2.0,Gồm 9 bàiBài 1: Đại cương về khoa học hành vi ...,"{""name"": ""Th\u00f4ng tin chung"", ""attributes"":...",156095.0,3.786614e+12,HaAnBooks,143850.0,6,"{'id': 86981323.0, 'publisher_vn': 'Công Ty Cổ..."

In [ ]:
ratings = pd.read_csv('/content/drive/MyDrive/Ky1nam4/DoAnCuoiKy/Data_final/data_final/content-based/final_reviews_than30.csv')
ratings

,id,product_id,user_id,user_name,rating,content,thank_count,rating_average,count
0,17456235,141483251.0,6001429.0,Mơ Mèo,5,NaN,0,4.9,1
1,14694996,141483251.0,14361212.0,Nguyễn Thanh Thế,5,sach hay,0,4.9,1
2,17865779,125362334.0,10025671.0,Nguyễn Thế Vi,5,NaN,0,4.8,1
3,16034964,58213080.0,7214085.0,Lê Thụy Bích Vân,5,Các bà mẹ có con nhỏ nên trang bị 1 cuốn nhé. ...,0,4.9,1
4,17380083,58213080.0,27633370.0,Thuỷ Tiên,5,"Sách nhẹ, chất lượng tốt",0,4.9,1
...,...,...,...,...,...,...,...,...,...
142257,16514730,37793725.0,1248889.0,Lê Hoài Thương,5,Sách rất bổ ích,0,4.8,1
142258,7962608,37793725.0,551813.0,Đinh Nho Anh,4,NaN,0,4.8,1
142259,3306921,37151279.0,16037020.0,Giuse Maria Vũ Trần,5,Thể loại tạp chí về y học rất hữu ích. Tiki đó...,0,4.7,1
142260,16804802,37151279.0,5647389.0,Minh Hieu Nguyen,5,NaN,0,4.7,1
142261,12396306,86981323.0,11976471.0,Giuse Hiền,5,NaN,0,5.0,1

In [ ]:
train_test = pd.read_csv('/content/drive/MyDrive/Ky1nam4/DoAnCuoiKy/Data_final/data_final/content-based/train_test_CB')
train_test

,user_id,train_list,test_list
0,27.0,"[76187993.0, 139567591.0, 35193352.0, 74217555...","[105375445.0, 155114509.0, 52273044.0, 1734795..."
1,247.0,"[652373.0, 167970787.0, 3981417.0, 55171098.0,...","[42872824.0, 54003813.0, 52111902.0, 36399672...."
2,745.0,"[52785564.0, 85350807.0, 10671292.0, 67120582....","[77702310.0, 71321829.0, 11419483.0, 77105740...."
3,1196.0,"[109515306.0, 32701102.0, 75454156.0, 33492447...","[54380460.0, 45613723.0, 57798819.0, 69701385...."
4,1654.0,"[148760915.0, 109515304.0, 132366467.0, 641906...","[130996082.0, 104074993.0, 23416722.0, 1115376..."
...,...,...,...
2734,27821791.0,"[66698352.0, 66698356.0, 193411736.0, 17848362...","[142833447.0, 106863963.0, 142833449.0, 133864..."
2735,28059010.0,"[181699688.0, 142833449.0, 127170155.0, 142833...","[4940237.0, 138269675.0, 97594364.0, 24594323...."
2736,28063351.0,"[120357410.0, 5068333.0, 4423761.0, 90679270.0...","[35240890.0, 110447680.0, 68049234.0, 10752043..."
2737,28092104.0,"[197601741.0, 171091440.0, 197634260.0, 193917...","[165030714.0, 193434490.0, 186267244.0, 193196..."
2738,28236424.0,"[130233544.0, 56692532.0, 7982628.0, 47342678....","[57587909.0, 7644510.0, 54433518.0, 87226756.0..."

In [ ]:
vectors = pd.read_csv('/content/drive/MyDrive/Ky1nam4/DoAnCuoiKy/Data_final/CB-sbert.csv', header = None)

In [ ]:
vectors = vectors.to_numpy()

In [ ]:
def Average(lst):
    return sum(lst) / len(lst)

### MRR

In [ ]:
result_list = []
for index in range(len(train_test.user_id)):
  vector_total = np.zeros(768)
  # print(id)
  list_train = eval(train_test[train_test.user_id == train_test.user_id[index]]
                    .train_list[index])
  len_train = len(list(books[books.id.isin(list_train)].index))
  for i in list(books[books.id.isin(list_train)].index):
    vector_total += vectors[i]
  vector_train = vector_total/len_train
  list_test = eval(train_test[train_test.user_id == train_test.user_id[index]]
                   .test_list[index])
  vector_test = vectors[list(books[books.id.isin(list_test)].index)]

  similarity_matrix = cosine_similarity(vector_train.reshape(1, -1), vector_test)
  result = 0.0
  for i in range(len(similarity_matrix[0])):
    if similarity_matrix[0][i] >= 0.5:
      result = 1/(i+1)
      break
      if i == len(similarity_matrix[0])-1:
        result = 0
    
  result_list.append(result)
print("Ket qua MRR: {}".format(round(Average(result_list), 2)))

Ket qua MRR: 0.93

### NDCG

In [ ]:
vector_total = np.zeros(768)
# print(id)
list_train = eval(train_test[train_test.user_id == 27.0].train_list[0])
len_train = len(list(books[books.id.isin(list_train)].index))
for i in list(books[books.id.isin(list_train)].index):
  vector_total += vectors[i]
vector_train = vector_total/len_train
list_test = eval(train_test[train_test.user_id == 27.0]
                  .test_list[0])
vector_test = vectors[list(books[books.id.isin(list_test)].index)]

similarity_matrix = cosine_similarity(vector_train.reshape(1, -1), vector_test)

In [ ]:
similarity_matrix[0].tolist()

In [ ]:
dict = {'relevance': similarity_matrix[0].tolist()} 
    
df = pd.DataFrame(dict)

In [ ]:
df['log2'] = np.log2(df.index + 2)
df['chia'] = df['relevance']/df['log2']
df['DCG'] = df['chia']

for i in range(len(df.DCG)):
  if i == 0:
    continue
  else:
    df['DCG'][i] += df['DCG'][i-1]
df['relevance'] = df['relevance'].sort_values(ascending=False).reset_index(drop = True)
df['chia2'] = df['relevance']/df['log2']
df['IDCG'] = df['chia2']
for i in range(len(df.IDCG)):
  if i == 0:
    continue
  else:
    df['IDCG'][i] += df['IDCG'][i-1]

df['NDCG'] = df['DCG']/df['IDCG']
df['NDCG'].mean()

0.7531066631398345

In [ ]:
result_list = []
for index in range(len(train_test.user_id)):
  vector_total = np.zeros(768)
  # print(id)
  list_train = eval(train_test[train_test.user_id == train_test.user_id[index]]
                    .train_list[index])
  len_train = len(list(books[books.id.isin(list_train)].index))
  for i in list(books[books.id.isin(list_train)].index):
    vector_total += vectors[i]
  vector_train = vector_total/len_train
  list_test = eval(train_test[train_test.user_id == train_test.user_id[index]]
                   .test_list[index])
  vector_test = vectors[list(books[books.id.isin(list_test)].index)]

  similarity_matrix = cosine_similarity(vector_train.reshape(1, -1), vector_test)
  #create dataframe
  dict = {'relevance': similarity_matrix[0].tolist()} 
  df = pd.DataFrame(dict)

  df['log2'] = np.log2(df.index + 2)
  df['chia'] = df['relevance']/df['log2']
  df['DCG'] = df['chia']

  for i in range(len(df.DCG)):
    if i == 0:
      continue
    else:
      df['DCG'][i] += df['DCG'][i-1]
  df['relevance'] = df['relevance'].sort_values(ascending=False).reset_index(drop = True)
  df['chia2'] = df['relevance']/df['log2']
  df['IDCG'] = df['chia2']
  for i in range(len(df.IDCG)):
    if i == 0:
      continue
    else:
      df['IDCG'][i] += df['IDCG'][i-1]

  df['NDCG'] = df['DCG']/df['IDCG']
  result_list.append(df['NDCG'].mean())
print("Ket qua NDCG: {}".format(round(Average(result_list), 2)))

Ket qua NDCG: 0.89

## TFIDF

In [ ]:
books.description = books.description.astype(str)
# books.title = books.title.astype(str)

In [ ]:
!pip -qq install pyvi

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.tokenize import word_tokenize
nltk.download('punkt')
from pyvi import ViTokenizer, ViPosTagger

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [ ]:
# viết hàm tiền xử lý dữ liệu trên cột overview

def Preprocessing(data):
  # stop_words = set(stopwords.words('english'))
  f = open("/content/drive/MyDrive/Ky1nam4/stopwords/vietnamese.txt", "r")
  stop_words = set(f.read())
#  - chuyển về từ thường
  ii = 1
  for i in range(len(data)):
#  - Xóa dấu câu, ký tự đặc biệt
#  - xóa stopword
#  - tách từ
#  ...
    if ii % 1000 == 0:
      print(ii)
    ii += 1
    data[i] = re.sub('\W+', ' ', data[i].lower())
    tokens = ViTokenizer.tokenize(data[i])
    word_tokens = tokens.strip().split(' ')
    data[i] = [w for w in word_tokens if not w in stop_words]
    data[i] = ' '.join(data[i][:100])

In [ ]:
Preprocessing(books.description)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000

In [ ]:
#sử dụng TfidfVectorizer để chuyển cột overview của các bộ phim về tf-idf và lưu vào biến overview_matrix
from sklearn.feature_extraction.text import TfidfTransformer 
from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.feature_extraction.text import CountVectorizer

tfidf_vectorizer = TfidfVectorizer(ngram_range=[1, 1])
overview_matrix = tfidf_vectorizer.fit_transform(books.description)
# tfidf_vectorizer = TfidfVectorizer(ngram_range=[1, 1])

In [ ]:
overview_matrix = overview_matrix.toarray()

In [ ]:
result_list = []
# overview_matrix = overview_matrix.toarray()
for index in range(len(train_test.user_id)):
  vector_total = np.zeros(36957)
  # print(index)
  list_train = eval(train_test[train_test.user_id == train_test.user_id[index]]
                    .train_list[index])
  len_train = len(list(books[books.id.isin(list_train)].index))
  for i in list(books[books.id.isin(list_train)].index):
    vector_total += overview_matrix[i]
  vector_train = vector_total/len_train
  list_test = eval(train_test[train_test.user_id == train_test.user_id[index]]
                   .test_list[index])
  vector_test = overview_matrix[list(books[books.id.isin(list_test)].index)]

  similarity_matrix = cosine_similarity(vector_train.reshape(1, -1), vector_test)
  result = 0.0
  for i in range(len(similarity_matrix[0])):
    if similarity_matrix[0][i] >= 0.5:
      result = 1/(i+1)
      break
      if i == len(similarity_matrix[0])-1:
        result = 0
    
  result_list.append(result)
print("Ket qua MRR: {}".format(round(Average(result_list), 2)))

Ket qua MRR: 0.04

In [ ]:
result_list = []
# overview_matrix = overview_matrix.toarray()
for index in range(len(train_test.user_id)):
  vector_total = np.zeros(36957)
  # print(index)
  list_train = eval(train_test[train_test.user_id == train_test.user_id[index]]
                    .train_list[index])
  len_train = len(list(books[books.id.isin(list_train)].index))
  for i in list(books[books.id.isin(list_train)].index):
    vector_total += overview_matrix[i]
  vector_train = vector_total/len_train
  list_test = eval(train_test[train_test.user_id == train_test.user_id[index]]
                   .test_list[index])
  vector_test = overview_matrix[list(books[books.id.isin(list_test)].index)]

  similarity_matrix = cosine_similarity(vector_train.reshape(1, -1), vector_test)
  #create dataframe
  dict = {'relevance': similarity_matrix[0].tolist()} 
  df = pd.DataFrame(dict)

  df['log2'] = np.log2(df.index + 2)
  df['chia'] = df['relevance']/df['log2']
  df['DCG'] = df['chia']

  for i in range(len(df.DCG)):
    if i == 0:
      continue
    else:
      df['DCG'][i] += df['DCG'][i-1]
  df['relevance'] = df['relevance'].sort_values(ascending=False).reset_index(drop = True)
  df['chia2'] = df['relevance']/df['log2']
  df['IDCG'] = df['chia2']
  for i in range(len(df.IDCG)):
    if i == 0:
      continue
    else:
      df['IDCG'][i] += df['IDCG'][i-1]

  df['NDCG'] = df['DCG']/df['IDCG']
  result_list.append(df['NDCG'].mean())
print("Ket qua NDCG: {}".format(round(Average(result_list), 2)))

Ket qua NDCG: 0.75